output:main.o GTUSet.o GTUVector.o GTUIterator.o GTUIteratorConst.o
	g++ main.o GTUVector.o GTUIterator.o GTUIteratorConst.o -o output

main.o:main.cpp
	g++ -c main.cpp

GTUSet.o:GTUSet.cpp
	g++ -c GTUSet.cpp

GTUVector.o:GTUVector.cpp
	g++ -c GTUVector.cpp

GTUIterator.o:GTUIterator.cpp
	g++ -c GTUIterator.cpp
	
GTUIteratorConst.o:GTUIteratorConst.cpp
	g++ -c GTUIteratorConst.cpp