output:main.o BoardArray2d.o BoardArray1d.o BoardVector.o
	g++ main.o BoardArray2d.o BoardArray1d.o BoardVector.o -o output
	

main.o:main.cpp
	g++ -c main.cpp
BoardArray2d.o: BoardArray2d.cpp
	g++ -c BoardArray2d.cpp
BoardVector.o:BoardVector.cpp
	g++ -c BoardVector.cpp
BoardArray1d.o: BoardArray1d.cpp
	g++ -c BoardArray1d.cpp
